# Nix-based Docker image for development environments
# Uses dockerTools.buildLayeredImage with symlink-based home-manager integration
{
  inputs,
  lib,
  pkgs,
  ...
}: let
  user = "joshsymonds";
  uid = "1000";
  gid = "1000";
  homeDirectory = "/home/${user}";

  # Minimal locale configuration
  minimalLocales = pkgs.glibcLocales.override {
    locales = [
      "en_US.UTF-8/UTF-8"
      "C.UTF-8/UTF-8"
    ];
  };

  # Build home-manager activation package standalone
  homeConfig = import ./home-manager.nix {
    inherit inputs pkgs lib;
  };

  homeFiles = "${homeConfig.activationPackage}/home-files";

  # Core system packages needed in container
  systemPackages = with pkgs; [
    # Core utilities
    coreutils
    findutils
    gnugrep
    gnused
    gawk
    gnutar
    gzip
    which

    # Development tools
    git
    curl
    gcc
    docker-client
    kubectl
    helix

    # Custom packages
    claudeCodeCli
    _1password-cli

    # Shell
    zsh
    bashInteractive

    # Nix tools
    nix

    # Locales
    minimalLocales

    # SSL certificates
    cacert
  ];

  # Build a combined environment with all packages
  combinedEnv = pkgs.buildEnv {
    name = "egoengine-env";
    paths = systemPackages;
    pathsToLink = ["/bin" "/share" "/lib"];
  };

  # FHS-compatible directory structure
  # Coder agent init script expects /usr/bin/env, grep, tar, etc.
  fhsSetup = pkgs.runCommand "egoengine-fhs-setup" {} ''
        set -euo pipefail

        mkdir -p $out/usr/bin $out/bin $out/etc $out/home/${user}
        mkdir -p $out/etc/pam.d

        # /usr/bin symlinks (Coder agent compatibility)
        ln -s ${pkgs.coreutils}/bin/env $out/usr/bin/env
        ln -s ${pkgs.gnugrep}/bin/grep $out/usr/bin/grep
        ln -s ${pkgs.gnutar}/bin/tar $out/usr/bin/tar
        ln -s ${pkgs.gzip}/bin/gzip $out/usr/bin/gzip
        ln -s ${pkgs.coreutils}/bin/head $out/usr/bin/head
        ln -s ${pkgs.which}/bin/which $out/usr/bin/which
        ln -s ${pkgs.zsh}/bin/zsh $out/usr/bin/zsh
        ln -s ${pkgs.bashInteractive}/bin/bash $out/usr/bin/bash

        # /bin symlinks
        ln -s ${pkgs.bashInteractive}/bin/bash $out/bin/sh
        ln -s ${pkgs.coreutils}/bin/env $out/bin/env

        # User account files
        cat > $out/etc/passwd <<EOF
    root:x:0:0::/root:/bin/sh
    ${user}:x:${uid}:${gid}::${homeDirectory}:${pkgs.zsh}/bin/zsh
    EOF

        cat > $out/etc/group <<EOF
    root:x:0:
    ${user}:x:${gid}:${user}
    docker:x:998:${user}
    wheel:x:10:${user}
    EOF

        cat > $out/etc/shadow <<EOF
    root:!:1::::::
    ${user}:!:1::::::
    EOF

        cat > $out/etc/gshadow <<EOF
    root:!::
    ${user}:!::
    docker:!::${user}
    wheel:!::${user}
    EOF

        mkdir -p $out/etc/sudoers.d
        cat > $out/etc/sudoers <<EOF
    # Generated by egoengine docker image
    Defaults env_reset
    Defaults lecture = never
    Defaults secure_path="/usr/bin:/bin:/nix/var/nix/profiles/default/bin"

    root ALL=(ALL:ALL) ALL
    ${user} ALL=(ALL:ALL) NOPASSWD:ALL
    %wheel ALL=(ALL:ALL) NOPASSWD:ALL

    @includedir /etc/sudoers.d
    EOF
        chmod 0440 $out/etc/sudoers
        cat > $out/etc/pam.d/sudo <<EOF
    auth       sufficient ${pkgs.linux-pam}/lib/security/pam_permit.so
    account    sufficient ${pkgs.linux-pam}/lib/security/pam_permit.so
    password   sufficient ${pkgs.linux-pam}/lib/security/pam_permit.so
    session    sufficient ${pkgs.linux-pam}/lib/security/pam_permit.so
    EOF
        chmod 0644 $out/etc/pam.d/sudo

        chmod 0700 $out/home/${user}
  '';

  # Construct PATH for container
  containerPath = lib.concatStringsSep ":" [
    "${homeDirectory}/.nix-profile/bin"
    "${homeDirectory}/.local/bin"
    "/nix/var/nix/profiles/per-user/${user}/profile/bin"
    "${combinedEnv}/bin"
    "/usr/bin"
    "/bin"
  ];
in
  pkgs.dockerTools.buildLayeredImage {
    name = "egoengine";
    tag = "latest";

    enableFakechroot = true;
    fakeRootCommands = ''
      set -euo pipefail

      # Base directories
      mkdir -p ./home/${user} ./workspace ./tmp ./root
      mkdir -p ./nix/var/nix/profiles/per-user/${user}

      # Sudo with setuid
      cp ${pkgs.sudo}/bin/sudo ./usr/bin/sudo
      chown 0:0 ./usr/bin/sudo
      chmod 4755 ./usr/bin/sudo

      # ── Home directory setup ──
      # Mirrors home-manager activation: symlink managed files, real writable dirs.

      # 1. Create writable directories (these must be real, not symlinks)
      for dir in \
        .cache \
        .config \
        .local/bin \
        .local/share/atuin \
        .claude/debug \
        .rbenv/shims \
        .rbenv/versions \
        .ssh \
      ; do
        mkdir -p "./home/${user}/$dir"
      done

      # 2. Symlink managed dotfiles from home-manager (like activation does)
      #    Walk home-files and recreate the structure with symlinks.
      #    Uses -printf '%P\n' for relative paths (find resolves starting symlinks,
      #    so absolute paths won't match the original prefix).
      cd ./home/${user}
      ${pkgs.findutils}/bin/find ${homeFiles}/ -mindepth 1 \( -type f -o -type l \) -printf '%P\n' | while IFS= read -r rel; do
        dir="$(dirname "$rel")"

        # Create parent directories (as real dirs, not symlinks)
        if [ "$dir" != "." ]; then
          mkdir -p "$dir"
        fi

        # Don't overwrite writable directories with symlinks
        if [ ! -d "$rel" ]; then
          ln -sf "${homeFiles}/$rel" "$rel"
        fi
      done
      cd /

      # 3. Home-manager profile (provides binaries via ~/.nix-profile/bin)
      ln -sf ${homeConfig.activationPackage}/home-path ./nix/var/nix/profiles/per-user/${user}/profile
      ln -sf /nix/var/nix/profiles/per-user/${user}/profile ./home/${user}/.nix-profile

      # ── Permissions ──
      chown -R ${uid}:${gid} ./home/${user}
      chmod 0700 ./home/${user}
      chown ${uid}:${gid} ./workspace
      chmod 0755 ./workspace
      chmod 1777 ./tmp
      chown ${uid}:${gid} ./nix/var/nix/profiles/per-user/${user}
    '';

    contents = [
      fhsSetup
      pkgs.dockerTools.usrBinEnv
      pkgs.dockerTools.binSh
      pkgs.dockerTools.caCertificates
      pkgs.dockerTools.fakeNss
      combinedEnv
      homeConfig.activationPackage
    ];

    config = {
      User = user;
      WorkingDir = homeDirectory;
      Cmd = ["${pkgs.zsh}/bin/zsh" "-l"];

      Env = [
        "USER=${user}"
        "HOME=${homeDirectory}"
        "SHELL=${pkgs.zsh}/bin/zsh"
        "LANG=en_US.UTF-8"
        "LC_ALL=en_US.UTF-8"
        "EDITOR=hx"
        "PATH=${containerPath}"
        "NIX_CONFIG=experimental-features = nix-command flakes"
        "NIX_USER_PROFILE_DIR=/nix/var/nix/profiles/per-user/${user}"
        "NIX_PROFILES=/nix/var/nix/profiles/per-user/${user}/profile"
        "LOCALE_ARCHIVE=${minimalLocales}/lib/locale/locale-archive"
        "NO_COLOR=1"
      ];

      Labels = {
        "org.opencontainers.image.title" = "egoengine";
        "org.opencontainers.image.description" = "Nix-based development environment";
        "org.opencontainers.image.source" = "https://github.com/joshsymonds/nix-config";
        "org.opencontainers.image.licenses" = "MIT";
      };
    };
  }
