{
  lib,
  config,
  pkgs,
  hostname ? null,
  ...
}: let
  isDarwin = pkgs.stdenv.isDarwin;
  autoAttachRemoteTmux = hostname != null && !isDarwin;

  # Pre-render shell-init scripts at Nix build time so each new zsh sources
  # an immutable /nix/store/.../*.zsh instead of forking the helper binary.
  # Cache is invalidated automatically because rebuilding with a new helper
  # version produces a new store path. brew shellenv is rendered at
  # activation time instead (see home.activation.cacheBrewShellenv) because
  # /opt/homebrew is unavailable in the Nix build sandbox.
  # atuin's `init zsh` touches $HOME to ensure a config dir exists; the Nix
  # sandbox sets $HOME=/homeless-shelter which is read-only. Give helpers a
  # throwaway HOME so they don't crash on first run.
  preRender = name: cmd:
    pkgs.runCommand "${name}.zsh" {} ''
      export HOME=$(mktemp -d)
      ${cmd} > $out
    '';
  starshipInit = preRender "starship-init" "${config.programs.starship.package}/bin/starship init zsh";
  atuinInit = preRender "atuin-init" "${config.programs.atuin.package}/bin/atuin init zsh";
  direnvInit = preRender "direnv-init" "${config.programs.direnv.package}/bin/direnv hook zsh";
  zoxideInit = preRender "zoxide-init" "${config.programs.zoxide.package}/bin/zoxide init zsh";
  rbenvBin = "${config.programs.rbenv.package}/bin/rbenv";
  brewShellenvCache = "${config.xdg.cacheHome}/zsh/brew-shellenv.zsh";
in {
  home.sessionVariables =
    {
      NIX_CONFIG = "experimental-features = nix-command flakes";
      ZVM_CURSOR_STYLE_ENABLED = "false";
      XL_SECRET_PROVIDER = "FILE";
      WINEDLLOVERRIDES = "d3dcompiler_47=n;d3d11=n,b";
      # fd-backed fzf file search (Ctrl-T and the default `**`-completion
      # source). Written out identically in both vars rather than having
      # one reference the other — home.sessionVariables' export order isn't
      # guaranteed to put FZF_DEFAULT_COMMAND before FZF_CTRL_T_COMMAND.
      FZF_DEFAULT_COMMAND = "fd --type f --strip-cwd-prefix --hidden --exclude .git";
      FZF_CTRL_T_COMMAND = "fd --type f --strip-cwd-prefix --hidden --exclude .git";
    }
    // lib.optionalAttrs pkgs.stdenv.isLinux {
      PRISMA_SCHEMA_ENGINE_BINARY = "${pkgs.prisma-engines}/bin/schema-engine";
      PRISMA_QUERY_ENGINE_LIBRARY = "${pkgs.prisma-engines}/lib/libquery_engine.node";
      PRISMA_QUERY_ENGINE_BINARY = "${pkgs.prisma-engines}/bin/query-engine";
      PRISMA_FMT_BINARY = "${pkgs.prisma-engines}/bin/prisma-fmt";
    };

  xdg.configFile."zsh" = {
    source = ./zsh;
    recursive = true;
  };

  programs.zsh = {
    enable = true;
    enableCompletion = true;
    # Skip compaudit (saves ~50ms per shell). fpath is Nix-managed, so the
    # security check it would perform is moot.
    completionInit = ''
      autoload -Uz compinit
      compinit -C -d ''${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump
    '';
    dotDir = "${config.xdg.configHome}/zsh";

    historySubstringSearch.enable = true;

    syntaxHighlighting.enable = true;

    autosuggestion.enable = true;

    shellAliases = {
      ll = "eza -a -F -l -B --git";
      ls = "ls --color=auto";
      agenix = "agenix -i ~/.config/agenix/keys.txt";
    };

    envExtra = ''
      ${lib.optionalString isDarwin ''
        # Homebrew on Apple Silicon (cached output, regenerated by home-manager activation)
        [ -r "${brewShellenvCache}" ] && source "${brewShellenvCache}"
      ''}

      # GPG agent needs this to find the terminal for pinentry
      export GPG_TTY=$(tty)

      # Only set LS_COLORS if vivid is available
      if command -v vivid &>/dev/null; then
        export LS_COLORS="$(vivid generate catppuccin-mocha)"
      fi

      # Source secrets file if it exists
      [ -f ~/.secrets ] && source ~/.secrets

      # Source local environment overrides (used by child container images)
      [ -f ~/.env.local ] && source ~/.env.local
    '';

    history = {
      size = 50000;
      save = 50000;
      path = "${config.xdg.dataHome}/zsh/history";
    };

    initContent = ''
      # The patchbay CLI (contexts/routes/resolve/project) authenticates to
      # the local gateway with the caller key, located via this path-valued
      # variable. Claude Code gets the same key as a request header through
      # its rendered settings.json (see ccrender in
      # home-manager/claude-code), never from the shell. Exported only on
      # hosts that run a local patchbay.
      ${lib.optionalString (config.services.patchbay.enable or false) ''
        export PATCHBAY_CALLER_KEY_FILE=/run/agenix/patchbay-caller-key
      ''}

      t() {
        if [[ $# -eq 0 ]]; then
          tmux-devspace new
          return
        fi

        if [[ "$1" == "--" ]]; then
          shift
          tmux-devspace new "$@"
          return
        fi

        if [[ "$1" == -* ]]; then
          tmux-devspace new "$@"
          return
        fi

        local label="$1"
        shift

        local icon_flag=""
        local icon_value=""
        if [[ $# -gt 0 && "$1" != "--" ]]; then
          icon_flag="--icon"
          icon_value="$1"
          shift
        fi

        if [[ $# -gt 0 && "$1" == "--" ]]; then
          shift
        fi

        if [[ $# -gt 0 ]]; then
          if [[ -n "$icon_flag" ]]; then
            tmux-devspace attach "$icon_flag" "$icon_value" "$label" -- "$@"
          else
            tmux-devspace attach "$label" -- "$@"
          fi
        else
          if [[ -n "$icon_flag" ]]; then
            tmux-devspace attach "$icon_flag" "$icon_value" "$label"
          else
            tmux-devspace attach "$label"
          fi
        fi
      }

      ${lib.optionalString autoAttachRemoteTmux ''
        # Auto-attach to tmux ONLY when this shell was started by an
        # incoming SSH connection — i.e. someone SSH'd into this host and
        # we want them dropped into the long-lived `main` session managed
        # by the systemd tmux user service. Local terminal emulators
        # (kitty, etc.) get a plain zsh and use the emulator's own tabs
        # for multiplexing.
        # No exec — shell survives if tmux dies, so kill-server is safe.
        # -A: attach if main exists, create if not — no dependency on systemd pre-creating it.
        if [[ $- == *i* ]] && [[ -z "''${TMUX:-}" ]] && [[ -n "''${SSH_CONNECTION:-}" ]] && [[ "''${NO_REMOTE_TMUX:-0}" != 1 ]]; then
          tmux new-session -A -s main
        fi
      ''}

      # Disable mouse reporting in shell when not in tmux
      # This prevents raw mouse escape sequences from appearing
      if [ -z "$TMUX" ] && [ -n "$SSH_TTY" ]; then
        printf '\e[?1000l'  # Disable mouse tracking
        printf '\e[?1002l'  # Disable cell motion tracking
        printf '\e[?1003l'  # Disable all motion tracking
        printf '\e[?1006l'  # Disable SGR extended mode
      fi

      # Import dev context metadata from tmux environment if we're in tmux
      if [ -n "$TMUX" ]; then
        TMUX_DEVSPACE=$(tmux show-environment TMUX_DEVSPACE 2>/dev/null | cut -d= -f2)
        if [ -n "$TMUX_DEVSPACE" ]; then
          export TMUX_DEVSPACE
        fi

        DEV_CONTEXT=$(tmux show-environment DEV_CONTEXT 2>/dev/null | cut -d= -f2)
        if [ -n "$DEV_CONTEXT" ]; then
          export DEV_CONTEXT
        fi

        DEV_CONTEXT_ICON=$(tmux show-environment DEV_CONTEXT_ICON 2>/dev/null | cut -d= -f2)
        if [ -n "$DEV_CONTEXT_ICON" ]; then
          export DEV_CONTEXT_ICON
        fi
      fi

      # Derive a unified dev context for prompts and titles
      if [ -n "''${CODER_WORKSPACE_NAME:-}" ]; then
        export DEV_CONTEXT="$CODER_WORKSPACE_NAME"
        : "''${DEV_CONTEXT_KIND:=coder}"
        export DEV_CONTEXT_KIND
      elif [ -n "''${TMUX_DEVSPACE:-}" ]; then
        export DEV_CONTEXT="$TMUX_DEVSPACE"
        : "''${DEV_CONTEXT_KIND:=tmux}"
        export DEV_CONTEXT_KIND
      else
        if [ -z "''${DEV_CONTEXT:-}" ]; then
          DEV_CONTEXT="$(hostname -s 2>/dev/null || hostname 2>/dev/null || echo host)"
          export DEV_CONTEXT
          : "''${DEV_CONTEXT_KIND:=host}"
          export DEV_CONTEXT_KIND
        fi
      fi

      # SSH agent is now managed by systemd (Linux) or launchd (macOS)
      # Keys are automatically loaded by the ssh-agent service
      # Use 'ssh-add-git-keys' to manually reload keys if needed

      function set-title-precmd() {
        printf "\e]2;%s\a" "''${PWD/#$HOME/~}"
      }

      function set-title-preexec() {
        printf "\e]2;%s\a" "$1"
      }

      autoload -Uz add-zsh-hook
      add-zsh-hook precmd set-title-precmd
      add-zsh-hook preexec set-title-preexec

      function _tmux_devspace_autoname_precmd() {
        if [ -n "$TMUX" ] && [ "''${TMUX_AUTO_NAME:-0}" = "1" ] && command -v tmux-devspace >/dev/null 2>&1; then
          tmux-devspace rename >/dev/null 2>&1 || true
        fi
      }

      function _tmux_devspace_autoname_preexec() {
        if [ -n "$TMUX" ] && [ "''${TMUX_AUTO_NAME:-0}" = "1" ] && command -v tmux-devspace >/dev/null 2>&1; then
          tmux-devspace rename "$1" >/dev/null 2>&1 || true
        fi
      }

      add-zsh-hook precmd _tmux_devspace_autoname_precmd
      add-zsh-hook preexec _tmux_devspace_autoname_preexec

      # Ensure emacs mode (not vi mode)
      bindkey -e

      # rbenv lazy-load: defer the ~140ms init until first ruby/rbenv command.
      # On first call, the stub unfunctions itself, runs the real init, then
      # re-execs the originally-typed command via the now-installed shim.
      __rbenv_init() {
        unfunction rbenv ruby gem bundle 2>/dev/null
        eval "$(${rbenvBin} init - zsh)"
      }
      rbenv()  { __rbenv_init; rbenv  "$@"; }
      ruby()   { __rbenv_init; ruby   "$@"; }
      gem()    { __rbenv_init; gem    "$@"; }
      bundle() { __rbenv_init; bundle "$@"; }

      if [ -n "''${commands[fzf-share]}" ]; then
        source "$(fzf-share)/key-bindings.zsh"
        source "$(fzf-share)/completion.zsh"
      fi

      if type it &>/dev/null; then
        # Only source brew completions on macOS where brew is available
        if [[ "$(uname)" == "Darwin" ]] && type brew &>/dev/null; then
          source $(brew --prefix)/share/zsh/site-functions/_it
        fi
        eval "$(it wrapper)"
      fi

      export PATH=''${PATH}:''${HOME}/go/bin:''${HOME}/.local/share/../bin

      if [[ -z ''${EE_SYNCED-} && -x ''${HOME}/.local/bin/ee && -n ''${OP_SERVICE_ACCOUNT_TOKEN-} ]]; then
        "''${HOME}/.local/bin/ee" sync --quiet || true
        export EE_SYNCED=1
      fi

      ${lib.optionalString (!isDarwin) ''
        # Start atuin daemon if not running (for containers without systemd).
        # macOS uses launchd, so this fallback is gated to Linux.
        if command -v atuin &>/dev/null && ! pgrep -x "atuin" &>/dev/null; then
          mkdir -p ~/.local/share/atuin
          (atuin daemon &>/dev/null &)
        fi
      ''}

      # Pre-rendered helper inits (replace enableZshIntegration auto-evals).
      # Sourced last so atuin's Ctrl-R binding wins over fzf-history-widget,
      # matching the original auto-eval ordering at the bottom of zshrc.
      source ${starshipInit}
      source ${atuinInit}
      source ${direnvInit}
      source ${zoxideInit}
    '';
  };

  # Cache `brew shellenv` output once per home-manager activation. Cannot use
  # pkgs.runCommand here because /opt/homebrew is unreachable from the Nix
  # build sandbox; activation runs with the real $HOME and PATH.
  home.activation.cacheBrewShellenv = lib.mkIf isDarwin (lib.hm.dag.entryAfter ["writeBoundary"] ''
    if [ -x /opt/homebrew/bin/brew ]; then
      run mkdir -p "$(dirname "${brewShellenvCache}")"
      run /opt/homebrew/bin/brew shellenv > "${brewShellenvCache}"
    fi
  '');
}
